trigger:
- master

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/jobs/package.yml

- stage: Release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Release'], true))
  jobs:
    #Your build pipeline references an undefined variable named ‘githubPAT’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab. See https://go.microsoft.com/fwlink/?linkid=865972
  - deployment: GitHub
    environment: production
    pool:
      vmImage: vs2017-win2016
    strategy:
      runOnce:
        deploy:    
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: Download artifacts
          - powershell: |
              $version = (Get-ChildItem $Env:SYSTEM_ARTIFACTSDIRECTORY -Recurse -Filter "*.whl" | % {$_.Name -replace '^noelbundick-(.*?)-.*', '$1' })
              Write-Host "##vso[task.setvariable variable=version;isSecret=false;isOutput=true;]$version"
            displayName: 'Capture extension version from wheel'
          - task: jakobehn.jakobehn-vsts-github-tasks.publish-github-release.PublishGitHubRelease@0
            displayName: 'Publish GitHub Release'
            inputs:
              applicationName: 'VSTS-noelbundick'
              token: '$(githubPAT)'
              repo: 'azure-cli-extension-noelbundick'
              owner: noelbundick
              tagName: 'v$(extensionVersion.version)'
              releaseName: 'v$(extensionVersion.version)'
              releaseBody: |
                ```bash
                az extension add --source https://github.com/noelbundick/azure-cli-extension-noelbundick/releases/download/v$(extensionVersion.version)/noelbundick-$(extensionVersion.version)-py2.py3-none-any.whl
                ```
              Docker: '[acanthamoeba/azure-cli-extension-noelbundick](https://hub.docker.com/r/acanthamoeba/azure-cli-extension-noelbundick/)'
              draft: true
              prerelease: true
              assetsPattern: '$(System.ArtifactsDirectory)\azure-cli-extension-noelbundick\drop\*.whl'

  - deployment: Docker
    environment: production
    pool:
      vmImage: ubuntu-16.04
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: Download artifacts
          - powershell: |
              $version = (Get-ChildItem $Env:SYSTEM_ARTIFACTSDIRECTORY -Recurse -Filter "*.whl" | % {$_.Name -replace '^noelbundick-(.*?)-.*', '$1' })
              Write-Host "##vso[task.setvariable variable=version;isSecret=false;isOutput=true;]$version"
            displayName: 'Capture extension version from wheel copy'

          - task: Docker@0
            displayName: 'Build image'
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryConnection: acanthamoeba
              dockerFile: '**/vsts.Dockerfile'
              imageName: 'acanthamoeba/azure-cli-extension-noelbundick'
              qualifyImageName: false
              additionalImageTags: 'v$(extensionVersion.version)'
              includeLatestTag: true

          - task: Docker@0
            displayName: 'Publish to Docker Hub'
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryConnection: acanthamoeba
              action: 'Push an image'
              imageName: 'acanthamoeba/azure-cli-extension-noelbundick'
              additionalImageTags: 'v$(extensionVersion.version)'
              includeLatestTag: true
