trigger:
- master

stages:
- stage: Build
  jobs:
  - template: .azure-pipelines/jobs/build.yml

- stage: Release
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - template: .azure-pipelines/jobs/release.yml