on:
  push:
    branches:
      - "*"
    tags:
      - "v*"

env:
  IMAGE: acanthamoeba/azure-cli-extension-noelbundick

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - run: |
        python -m pip install pylint flake8
        pylint src
        flake8 src

    - run: |
        cd src/noelbundick
        python -m pip install -U pip wheel
        python setup.py bdist_wheel -d "$GITHUB_WORKSPACE/dist"
        
        WHEEL=$(find ./dist -name "*.whl" -printf "%f")
        echo "::set-env name=WHEEL::$WHEEL"

    - run: |
        az extension add -s $WHEEL -y
        az extension list

    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist

    - id: validate_release
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        VERSION=$(echo $WHEEL | grep -Po '\w+-\K(\d+\.*)+')
        if [ "refs/tags/v$VERSION" != "$GITHUB_REF" ]; then
          echo "The source control tag does not match the version specified for the wheel. Did you remember to update setup.py?"
          echo "Tag: $GITHUB_REF"
          echo "Wheel: $VERSION"
          exit 1
        fi

    - id: create_release
      uses: actions/create-release@v1
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: |
          ```bash
          az extension add --source https://github.com/noelbundick/azure-cli-extension-noelbundick/releases/download/${{ github.ref }}/${{ env.WHEEL }}
          ```
        draft: true
        prerelease: true

    - uses: actions/upload-release-asset@v1
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/${{ env.WHEEL }}
        asset_name: ${{ env.WHEEL }}
        asset_content_type: application/zip
